-- LAYER: 02 Intermediate
-- MODEL: Daily Aggregated Flags (Cases Only)
-- PURPOSE: Aggregates the base table to daily sums, filtering only for users who had a case.
-- TARGET: CX_ANALYTICS_DEV.JEREMIAH_DEV_EXPLORATORY.CXCAT_712_DAILY_AGGREGATED_TRINITY_FLAGS_CASES_ONLY

CREATE OR REPLACE VIEW CX_ANALYTICS_DEV.JEREMIAH_DEV_EXPLORATORY.CXCAT_712_DAILY_AGGREGATED_TRINITY_FLAGS_CASES_ONLY AS
SELECT
    DATE_KEY,
    
    -- 1. Volume Metric: Unique users with a case in this filtered set
    COUNT(DISTINCT SONOS_ID) AS TOTAL_USERS_WITH_CASES,

    -- 2. Aggregated Error Counts (Only for users with cases)
    SUM(HHH_SETUP_WIZARD_ERROR) AS TOTAL_SETUP_WIZARD_ERRORS,
    SUM(HHH_ADD_PRODUCT_ERROR) AS TOTAL_ADD_PRODUCT_ERRORS,
    SUM(HHH_PLAY_GT_1_SECONDS) AS TOTAL_PLAY_GT_1_SEC_ERRORS,
    SUM(HHH_SONOS_FAVORITES_GT_10_SECONDS) AS TOTAL_FAVORITES_GT_10_SEC,
    SUM(HHH_YOUR_SOURCES_GT_10_SECONDS) AS TOTAL_SOURCES_GT_10_SEC,
    SUM(HHH_YOUR_SERVICES_GT_10_SECONDS) AS TOTAL_SERVICES_GT_10_SEC,
    SUM(HHH_SPOTIFY_PLAYREPORT) AS TOTAL_SPOTIFY_PLAY_ERRORS,
    SUM(HHH_RECENTLY_PLAYED_GT_10_SECONDS) AS TOTAL_RECENTLY_PLAYED_GT_10_SEC,
    SUM(HHH_SETGROUPMEMBERS_GT_4_SECONDS) AS TOTAL_SET_GROUP_GT_4_SEC,
    SUM(HHH_GENERIC_ERROR_TOAST) AS TOTAL_GENERIC_ERROR_TOASTS,
    SUM(HHH_PINNED_FAVORITES_LOAD) AS TOTAL_PINNED_FAVORITES_LOAD_ERRORS,
    SUM(HHH_LOADCONTENT_GT_2_SECONDS) AS TOTAL_LOAD_CONTENT_GT_2_SEC,
    SUM(HHH_SONOS_RADIO_PLAYREPORT) AS TOTAL_SONOS_RADIO_ERRORS,
    SUM(HHH_AIRPLAY_PLAYREPORT) AS TOTAL_AIRPLAY_ERRORS,

    -- 3. Outcome Metrics
    SUM(CX_CASE_WITHIN_7_DAYS) AS CONFIRMED_CASE_COUNT, 
    SUM(PCS_COMPLETED) AS TOTAL_PCS_SURVEYS_COMPLETED

FROM
    CX_ANALYTICS_DEV.JEREMIAH_DEV_EXPLORATORY.CXCAT_712_DATA_TRINITY_FLAGS
WHERE 
    CX_CASE_WITHIN_7_DAYS = 1
GROUP BY
    DATE_KEY
ORDER BY 
    DATE_KEY ASC;
