-- LAYER: 03 Presentation
-- MODEL: Tableau Tall View
-- PURPOSE: Unpivots the daily aggregated error counts into a "Tall" format for Tableau visualization.
-- TARGET: CX_ANALYTICS_DEV.JEREMIAH_DEV_EXPLORATORY.CXCAT_712_DAILY_AGGREGATED_TRINITY_FLAGS_TALL

CREATE OR REPLACE VIEW CX_ANALYTICS_DEV.JEREMIAH_DEV_EXPLORATORY.CXCAT_712_DAILY_AGGREGATED_TRINITY_FLAGS_TALL AS
SELECT
    DATE_KEY,
    TOTAL_USERS_WITH_CASES,
    CONFIRMED_CASE_COUNT,
    TOTAL_PCS_SURVEYS_COMPLETED,
    ERROR_NAME,
    ERROR_COUNT
FROM CX_ANALYTICS_DEV.JEREMIAH_DEV_EXPLORATORY.CXCAT_712_DAILY_AGGREGATED_TRINITY_FLAGS_CASES_ONLY
UNPIVOT (
    ERROR_COUNT FOR ERROR_NAME IN (
        TOTAL_SETUP_WIZARD_ERRORS,
        TOTAL_ADD_PRODUCT_ERRORS,
        TOTAL_PLAY_GT_1_SEC_ERRORS,
        TOTAL_FAVORITES_GT_10_SEC,
        TOTAL_SOURCES_GT_10_SEC,
        TOTAL_SERVICES_GT_10_SEC,
        TOTAL_SPOTIFY_PLAY_ERRORS,
        TOTAL_RECENTLY_PLAYED_GT_10_SEC,
        TOTAL_SET_GROUP_GT_4_SEC,
        TOTAL_GENERIC_ERROR_TOASTS,
        TOTAL_PINNED_FAVORITES_LOAD_ERRORS,
        TOTAL_LOAD_CONTENT_GT_2_SEC,
        TOTAL_SONOS_RADIO_ERRORS,
        TOTAL_AIRPLAY_ERRORS
    )
);
