-- LAYER: 01 Base
-- MODEL: CX Trinity Flags
-- PURPOSE: Create the base fact table joining Reliability, Cases, and Surveys at the User/Day level.
-- TARGET: CX_ANALYTICS_DEV.JEREMIAH_DEV_EXPLORATORY.CXCAT_712_DATA_TRINITY_FLAGS

CREATE OR REPLACE TABLE CX_ANALYTICS_DEV.JEREMIAH_DEV_EXPLORATORY.CXCAT_712_DATA_TRINITY_FLAGS AS
SELECT
    -- Dimensions
    TO_NUMBER(TO_CHAR(E.TIMESTAMP_UTC_DAY, 'YYYYMMDD')) AS DATE_KEY,
    CAST(E.SONOS_ID AS NUMBER(38,0)) AS SONOS_ID,
    
    -- Reliability Error Flags (HHH)
    -- CX Top Errors
    MAX(CASE WHEN E.ACTIVITY_NAME = 'measure_wizard_finish_time' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_SETUP_WIZARD_ERROR,
    MAX(CASE WHEN E.ACTIVITY_NAME = 'add_product' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_ADD_PRODUCT_ERROR,
    MAX(CASE WHEN E.ACTIVITY_NAME = 'play>1 seconds' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_PLAY_GT_1_SECONDS,
    MAX(CASE WHEN E.ACTIVITY_NAME = 'time_to_settle - sonos_favorites_swimlane>10 seconds' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_SONOS_FAVORITES_GT_10_SECONDS,
    MAX(CASE WHEN E.ACTIVITY_NAME = 'time_to_settle - your_sources_swimlane>10 seconds' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_YOUR_SOURCES_GT_10_SECONDS,
    MAX(CASE WHEN E.ACTIVITY_NAME = 'time_to_settle - your_services_swimlane>10 seconds' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_YOUR_SERVICES_GT_10_SECONDS,
    MAX(CASE WHEN E.ACTIVITY_NAME = 'Spotify - playReport' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_SPOTIFY_PLAYREPORT,
    MAX(CASE WHEN E.ACTIVITY_NAME = 'time_to_settle - recently_played_swimlane>10 seconds' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_RECENTLY_PLAYED_GT_10_SECONDS,
    MAX(CASE WHEN E.ACTIVITY_NAME = 'setGroupMembers>4 seconds' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_SETGROUPMEMBERS_GT_4_SECONDS,
    MAX(CASE WHEN E.ACTIVITY_NAME = 'generic_error_toast' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_GENERIC_ERROR_TOAST,

    -- Noteworthy HHH Errors (PD Top Errors)
    MAX(CASE WHEN E.ACTIVITY_NAME = 'pinned_favorites_load' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_PINNED_FAVORITES_LOAD,
    MAX(CASE WHEN E.ACTIVITY_NAME = 'loadContent>2 seconds' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_LOADCONTENT_GT_2_SECONDS,
    MAX(CASE WHEN E.ACTIVITY_NAME = 'Sonos Radio - playReport' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_SONOS_RADIO_PLAYREPORT,
    MAX(CASE WHEN E.ACTIVITY_NAME = 'AirPlay - playReport' AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 ELSE 0 END) AS HHH_AIRPLAY_PLAYREPORT,
    
    -- Support Case Flag (CSX)
    -- Logic: Case created within 7 days AFTER the unhealthy event
    MAX(CASE 
        WHEN C.CASE_NUMBER IS NOT NULL AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1 THEN 1 
        ELSE 0 
    END) AS CX_CASE_WITHIN_7_DAYS,

    -- Survey Flag (PCS)
    -- Logic: Survey linked to the specific Case Number found above
    MAX(CASE 
        WHEN C.CASE_NUMBER IS NOT NULL              -- Case Exists
         AND S.CASE_NUMBER IS NOT NULL              -- Survey Exists for that Case
         AND E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1    -- Event was Unhealthy
        THEN 1 
        ELSE 0 
    END) AS PCS_COMPLETED

FROM 
    PRODUCT_OWNER.RELIABILITY.HHH_DAILY_BY_ACTIVITY_NAME_SONOS_ID_AND_UNHEALTHY_ERRORS E
    
    -- Join 1: Match Cases in 7-day window
    LEFT JOIN DATA_WAREHOUSE.WAREHOUSE_CUSTOMER.VIZ_OWNER_CSX_CONTACT_CASES_VOC C
    ON CAST(E.SONOS_ID AS NUMBER(38,0)) = TRY_CAST(C.SONOS_ID AS NUMBER(38,0)) 
    AND C.CASE_CREATED_DATE_PT >= TO_DATE(E.TIMESTAMP_UTC_DAY)
    AND C.CASE_CREATED_DATE_PT <= DATEADD(day, 7, TO_DATE(E.TIMESTAMP_UTC_DAY))

    -- Join 2: Match Surveys to those Cases
    LEFT JOIN DATA_WAREHOUSE.WAREHOUSE_SURVEY.VIZ_POST_CONTACT_SURVEY S
    ON C.CASE_NUMBER = S.CASE_NUMBER

GROUP BY 
    TO_NUMBER(TO_CHAR(E.TIMESTAMP_UTC_DAY, 'YYYYMMDD')),
    CAST(E.SONOS_ID AS NUMBER(38,0));
